FROM cruizba/ubuntu-dind:noble-28.2.1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

COPY postStart.sh /usr/local/bin/postStart.sh
RUN chmod +x /usr/local/bin/postStart.sh

WORKDIR /workspace
CMD ["/bin/sh"]
